apiVersion: v1
kind: Service
metadata:
  name: frontservice
  labels:
    service: frontservice
    project: snackbar
spec:
  type: NodePort
  selector:
    service: frontservice
    project: snackbar
  ports:
    - port: 80
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontservice
  labels:
    service: frontservice
    project: snackbar
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontservice
      project: snackbar
  template:
    metadata:
      labels:
        service: frontservice
        project: snackbar
    spec:
      containers:
        - name: frontservice
          image: changsungbeom/cmsfront:0.0.4
          ports:
            - containerPort: 5000
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "100m"
