apiVersion: v1
kind: Service
metadata:
  name: authmodule
  labels:
    service: authmodule
    project: snackbar
spec:
  type: NodePort
  selector:
    service: authmodule
    project: snackbar
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authmodule
  labels:
    service: authmodule
    project: snackbar
spec:
  replicas: 1
  selector:
    matchLabels:
      service: authmodule
      project: snackbar
  template:
    metadata:
      labels:
        service: authmodule
        project: snackbar
    spec:
      containers:
        - name: authmodule
          image: egoomoy/auth-module:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "100m"
          envFrom:
          - configMapRef:
              name: spring-info
          - secretRef:
              name: mariadb-secret
