apiVersion: v1
kind: Service
metadata:
  name: filemodule
  labels:
    service: filemodule
    project: snackbar
spec:
  type: NodePort
  selector:
    service: filemodule
    project: snackbar
  ports:
    - port: 8084
      targetPort: 8084

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filemodule
  labels:
    service: filemodule
    project: snackbar
spec:
  replicas: 1
  selector:
    matchLabels:
      service: filemodule
      project: snackbar
  template:
    metadata:
      labels:
        service: filemodule
        project: snackbar
    spec:
      containers:
        - name: filemodule
          image: changsungbeom/file-module:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "100m"
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-info
                  key: db-source
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
          volumeMounts:
            - name: file-volume
              mountPath: /mnt/nas1
      volumes:
        - name: file-volume
          hostPath: 
            path: /Users/changsungbeom/next/files