apiVersion: v1
kind: Service
metadata:
  name: portalmodule
  labels:
    service: portalmodule
    project: snackbar
spec:
  type: NodePort
  selector:
    service: portalmodule
    project: snackbar
  ports:
    - port: 8082
      targetPort: 8082

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portalmodule
  labels:
    service: portalmodule
    project: snackbar
spec:
  replicas: 1
  selector:
    matchLabels:
      service: portalmodule
      project: snackbar
  template:
    metadata:
      labels:
        service: portalmodule
        project: snackbar
    spec:
      containers:
        - name: portalmodule
          image: changsungbeom/portal-module:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "100m"
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-info
                  key: db-source
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
