apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-nginx
  labels:
    project: snackbar
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 3g

spec:
  ingressClassName: nginx
  rules:
    # - host: -> domain이 없는 경우 생략가능
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontservice
                port:
                  number: 80
          - path: /auth-module
            pathType: Prefix
            backend:
              service:
                name: authmodule
                port:
                  number: 8080

          - path: /portal-module
            pathType: Prefix
            backend:
              service:
                name: portalmodule
                port:
                  number: 8082

          - path: /cms-module
            pathType: Prefix
            backend:
              service:
                name: cmsmodule
                port:
                  number: 8083

          - path: /file-module
            pathType: Prefix
            backend:
              service:
                name: filemodule
                port:
                  number: 8084