apiVersion: v1
kind: ConfigMap
metadata:
  name: my-nginx-conf
  namespace: my-ns
data:
  nginx-conf: |
    worker_processes  1;
    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;
        keepalive_timeout  65;
        server {
            listen       80;
            server_name  localhost;
            location / {
                index  index.html index.htm;
            }

            gzip  on;
            gzip_types application/vnd.apple.mpegurl;
                
            # common vod settings
            vod_metadata_cache metadata_cache 512m;
            vod_mapping_cache mapping_cache 5m;
            vod_response_cache response_cache 128m;
            vod_drm_info_cache drm_cache 64m;

            # common proxy settings
            proxy_connect_timeout 5;
            proxy_send_timeout 5;
            proxy_read_timeout 5;
            
            # common file caching / aio
            open_file_cache max=100 inactive=5m;
            open_file_cache_valid 2m;
            open_file_cache_min_uses 1;
            open_file_cache_errors on;
            aio on;

            location /content/ {
                    root /mnt/output/;
                    vod hls;
                    add_header Access-Control-Allow-Headers '*';
                    add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
                    add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
                    add_header Access-Control-Allow-Origin '*';
                    expires 100d;
            }
        }
    }
