apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: my-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      volumes:
        - name: nginx-main-conf-test
          configMap:
            name: my-nginx-conf
            items:
              - key: nginx-conf
                path: nginx.conf
        - name: nginx-hls-vol
          persistentVolumeClaim:
            claimName: nginx-hls-pvc
      containers:
        - name: nginx-test
          image: nginx:1.21.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-main-conf-test
              mountPath: /etc/nginx/nginx.conf # mount nginx-conf volumn to /etc/nginx/nginx.conf
              readOnly: true
              subPath: nginx.conf
            - name: nginx-hls-vol
              mountPath: /mnt/output
