---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-hls-pv
  labels:
    type: local
spec:
  storageClassName: hls-pv-class
  capacity:
    storage: 3Gi # 스토리지 용량 크기
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/plant/next3/files/vod/output" # Host에 저장될 스토리지 공간
