apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-hls-pvc
  namespace: my-ns
spec:
  storageClassName: hls-pv-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
