apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: ever-ns
spec:
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: "Cluster" # default - externalTrafficPolicy: "Cluster"
  ports:
    - name: http
      port: 80
      targetPort: http
