apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit
  annotations:
    kubernetes.io/ingress.class: kong
    default-priority: '910'
config:
  minute: 3
  policy: local
plugin: rate-limiting