apiVersion: v1
kind: Service
metadata:
  name: cmsmodule
  labels:
    service: cmsmodule
    project: snackbar
spec:
  type: NodePort
  selector:
    service: cmsmodule
    project: snackbar
  ports:
    - port: 8080
      targetPort: 8083

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmsmodule
  labels:
    service: cmsmodule
    project: snackbar
spec:
  replicas: 1
  selector:
    matchLabels:
      service: cmsmodule
      project: snackbar
  template:
    metadata:
      labels:
        service: cmsmodule
        project: snackbar
    spec:
      containers:
        - name: cmsmodule
          image: egoomoy/cms-module:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "100m"
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-info
                  key: db-source
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
